spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/calories_tracker
    username: writeYourUsername
    password: writeYourPassword
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true